### PR TITLE
Fix README : PHP syntax

### PR DESCRIPTION
**Pull request by thomasbisignani**
Just a little fix in the README, it misses two `)`

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Hi, it's not your fault obviously, but apparently this library's got some dependency issues and now the build won't succeed. I will merge your change anyway. Thanks!

**Comment by matthiasnoback** [comment]
Now that I'm looking at it, it seems the fix was not correct. There should be just one extra `)` and the line shouldn't be indented more than it currently is.

**Comment by xabbuh** [comment]
I think I would move each `array()` call into its own line which would increase readability massively.

**Comment by thomasbisignani** [comment]
Hi, ok @matthiasnoback for the build thx ;)

I modified my fix, and in my opinion, the correct syntax for the first argument should be : 

```php
array(
    array('array_node_1' => array('required_value_1' => 'original value')),
    array('array_node_1' => array('required_value_1' => 'final value'))
 ),
```

**Comment by matthiasnoback** [comment]
@xabbuh You're right, but for now it's fine I guess. Also, thanks @thomasbisignani.

**Pull request merged**
