### PR TITLE
Show configuration error on invalid

### PR DESCRIPTION
**Pull request by Soullivaneuh**
This permit an easier debug configuration.

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Thanks for reporting this. I see two issues:

1. The test suite fails ;) This is a simple thing to fix by the way.
2. I would prefer not to make the constraint object stateful. I.e. the error should not be kept in a property, but instead be passed around to the `fail()` method. You could simply override the `evaluate()` method and copy its structure from `PHPUnit_Framework_Constraint`. Then you can append the exception message to the `$description`.

**Comment by Soullivaneuh** [comment]
> The test suite fails ;) This is a simple thing to fix by the way.

Done.

> Then you can append the exception message to the $description.

I don't think so. The error message is only catched on `matches` method and no `$description` on this place.

**Comment by matthiasnoback** [comment]
Right, this is why I said you could override `evaluate()` and move the code from `matches()` into that method. Then you have full control over the `$description`.

**Comment by Soullivaneuh** [comment]
Oh ok, misunderstand. Will do it.

**Comment by matthiasnoback** [comment]
No problem, thanks!

**Comment by Soullivaneuh** [comment]
@matthiasnoback done.

**Comment by matthiasnoback** [comment]
Nice! Now there's one more thing: users can provide their own `$description` if they like, so instead of overwriting that value you should append it.

**Comment by Soullivaneuh** [comment]
@matthiasnoback done.

**Comment by matthiasnoback** [comment]
Excellent! I forgot one thing: it would be nice to see this change reflected in a unit test. Could you add this please?

**Comment by Soullivaneuh** [comment]
Don't know how to test the `fail` method to get back the description...

**Comment by matthiasnoback** [comment]
Good point :) See `Tests/PhpUnit/AbstractConfigurationTestCaseTest.php:62` and `Tests/PhpUnit/ConfigurationTestCaseTraitActual.php:61`. You can verify the exception message there. However, I see now that `assertConfigurationIsValid()` doesn't even allow passing in a `$description` so you can only test the case with the empty description.

**Comment by Soullivaneuh** [comment]
Ok I updated related test to check more precise message. :+1:

**Comment by matthiasnoback** [comment]
Awesome, thanks very much - it's a very useful addition.

**Comment by Soullivaneuh** [comment]
You're welcome. :+1:

**Pull request merged**
